tasks:
  - before: |
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
      sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
      sudo apt-get update
      sudo apt-get install -y azure-functions-core-tools-4
    init: npm install
    command: npm run build

vscode:
  extensions:
    - github.copilot
    - ms-azuretools.vscode-azurefunctions
    - esbenp.prettier-vscode