name: Deploy to Azure Functions

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 3horsepowerv8
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '14'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: npm build
      run: |
        npm set npm_config_arch ia32
        npm ci --arch=ia32
        npm run build
        
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
