name: Build Docker Image

on:
  push:
    paths:
      - "src/**"
      - "Dockerfile"
      - "**.json"
      - ".github/workflows/docker.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Install docker-slim
      run: brew install docker-slim

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Run docker-slim on image
      run: docker-slim build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Push image
      run: |
        docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}.slim ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
